{% set name = "pytrinamic" %}
{% set version = "0.2.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytrinamic-{{ version }}.tar.gz
  sha256: fddb683b4477e21c55f3366bf28e4c55eaf3c537a045c1d9d5ded2d48f3651c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - intelhex >=2.3
    - python >={{ python_min }}
    - python-can >=3
    - wrapt <2
    - canopen
    - pyserial >=3
    - intelhex >=2.3

test:
  imports:
    - pytrinamic
  commands:
    - tmclfwupload --help
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trinamic/PyTrinamic
  summary: TRINAMIC's Python Technology Access Package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
