{% set name = "pytrinamic" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytrinamic-{{ version }}.tar.gz
  sha256: 4b4a59976e5a3446c3fab6fbe761ffd88251dfe94754c14a5ac049c338b139cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-can >=3,<4
    - canopen
    - pyserial >=3

test:
  imports:
    - pytrinamic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trinamic/PyTrinamic
  summary: TRINAMIC's Python Technology Access Package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
