{% set name = "pytrinamic" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytrinamic-{{ version }}.tar.gz
  sha256: b4639d99d0e3747c3f0daaa65c29a6ec6233bc61c122afeecebeba50b11c6f6c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - intelhex >=2.3
    - python >=3.6
    - python-can >=3
    - canopen
    - pyserial >=3
    - msgpack-python

test:
  imports:
    - pytrinamic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trinamic/PyTrinamic
  summary: TRINAMIC's Python Technology Access Package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
