{% set name = "pytrinamic" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytrinamic-{{ version }}.tar.gz
  sha256: 75c5a33f6ed3de77b193f83fb23cdb1bb8cecbb8a78944f1dbeccdeb821f8ffb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - intelhex >=2.3
    - python >={{ python_min }}
    - python-can >=3
    - canopen
    - pyserial >=3
    - msgpack-python <=1.0

test:
  imports:
    - pytrinamic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trinamic/PyTrinamic
  summary: TRINAMIC's Python Technology Access Package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
